### PR TITLE
Defer running the state and action transforms

### LINKED ISSUE #6: stateTransformer Usage.
Hi - is there anyway to have this be called (or run) only if an error happens and only when the state is actually being submitted?

I ask because my state can get a little large and in testing I've occasionally hit the 'Request Entity too Large' error. So, I've set up a function that removes a couple of fields from my state before passing to Raven. But it is an iterative function and therefore potentially expensive so I'd prefer not to run it every time my state changes.

I guess I could use some shallow checking on the parts of the state I'm interested in, but I wonder if there's a better way?

### PR DESCRIPTION
**Pull request by captbaritone**
Fixes #6.

### CODE REVIEW

**Comment by captbaritone** [comment]
I will add some additional documentation to clarify how this works with user defined data callbacks and then cut a new release.

**Comment by captbaritone** [comment]
Thanks for prompting me to look into this again, and thanks for reviewing. 👏

**Comment by ChrisSargent** [comment]
No worries, thanks for the promptness!

**Comment by captbaritone** [comment]
Version `0.6.0` has been published.

**Pull request merged**
